- name: Add EULA
  template:
    src: eula.txt.j2
    dest: /home/{{ username }}/eula.txt

- name: Add server.properties
  template:
    src: server.properties.j2
    dest: /home/{{ username }}/server.properties

- name: Download Server 1.18.2
  ansible.builtin.get_url:
    url: https://api.papermc.io/v2/projects/paper/versions/1.18.2/builds/387/downloads/paper-1.18.2-387.jar
    dest: /home/{{ username }}/paper-{{ version }}.jar
  when: version == 1.18

- name: Download Server 1.19.2
  ansible.builtin.get_url:
    url: https://api.papermc.io/v2/projects/paper/versions/1.19.2/builds/130/downloads/paper-1.19.2-130.jar
    dest: /home/{{ username }}/paper-{{ version }}.jar
  when: version == 1.19

- name: Server running msg
  ansible.builtin.debug:
    msg: Server will be running shortly - Press CTRL+C to exit this session (The server will NOT be stopped)

- name: Run Server
  ansible.builtin.shell: nohup java -Xms2G -Xmx2G -jar /home/{{ username }}/paper-{{ version }}.jar --nogui